baseURL = "/"
languageCode = "en-us"
title = "Wil Scott - Terminal Portfolio"
# theme = ""

# Disable default pages
disableKinds = ["taxonomy", "term"]

# Menus for navigation
[menu]  
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url  = "/blog/"      # The blog section listing
    weight = 3
  [[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Optional: Enable syntax highlighting in blog posts (if you have code snippets in posts)
[markup]
  [markup.highlight]
    style = "monokai"
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Interactive terminal-based portfolio for Wil Scott, software engineer specializing in C, C++, Python, and scripting"
  author = "Wil Scott"
