baseURL = 'https://wil-scott.com/'
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Hi! I'm Wilson."

theme = 'gokarna'

enableRobotsTXT = true

[menu]
	[[menu.main]]
		identifier = "CV"
		url = "/cv/"
		name = "CV"
		pre = "<span data-feather='briefcase'></span>"
		weight = 1
	
	[[menu.main]]
		identifier = "info"
		url = "/info/"
		name = "info"
		pre = "<span data-feather='info'></span>"
		weight = 2

	[[menu.main]]
		identifier = "projects"
		url = "/projects/"
		name = "projects"
		pre = "<span data-feather='code'></span>"
		weight = 3

	[[menu.main]]
		identifier = "posts"
		url = "/posts/"
		name = "Posts"
		pre = "<span data-feather='book-open'></span>"
		weight = 4
	
	[[menu.main]]
		identifier = "github"
		url = "https://github.com/wil-scott"
		pre = "<span data-feather='github'></span>"
		weight = 5

	[[menu.main]]
		identifier = "LinkedIn"
		url = "https://www.linkedin.com/in/wil-scott/"
		pre = "<span data-feather='linkedin'></span>"
		weight = 6

[params]
	customHeadHTML = '''
		<link rel="stylesheet" href="/css/styles.css">
	'''

	avatarURL = "/images/avatar.png"

	avatarSize = "size-l"

	description = "Software developer, tinkerer, single-board computer enthusiast." 	

	socialIcons = [
		{name = "linkedin", url = "https://www.linkedin.com/in/wil-scott/"},
		{name = "github", url = "https://github.com/wil-scott"},
	]
	
	accentColor = "#FF4D4D"
	
	ShowBackToTopButton = true
	
	footer = "Wilson Scott"
	
